version: 'build-{build}-{branch}'

platform: x64

configuration:
  - Release

build:
  parallel: true

image:
  - Visual Studio 2019

environment:
  SHELL: "windows"
  matrix:
    - GENERATOR: "Visual Studio 16 2019"
      BUILDFLAGS: "/verbosity:normal"
      CMAKEARGS: "-DVCPKG_TARGET_TRIPLET=x64-windows"

matrix:
  fast_finish: true

install:
- git clone https://github.com/microsoft/vcpkg.git
- cd vcpkg
- ./bootstrap.bat
- vcpkg install
- cd %APPVEYOR_BUILD_FOLDER%
- git submodule update --init --depth 1 --recursive


before_build:
  - cmake --version

build_script:
  - cmake -S. -Bbuild
          -G"%GENERATOR%"
          -A x64
          -DCMAKE_BUILD_TYPE=%CONFIGURATION%
          %CMAKEARGS%
  - cmake --build build
          --config %CONFIGURATION%
          -- %BUILDFLAGS%

deploy: off
