version: 'build-{build}-{branch}'

platform: x64

configuration:
  - Release

build:
  parallel: true

image:
  - Visual Studio 2019

environment:
  SHELL: "windows"
  BOOST_ROOT: C:/Libraries/boost_1_73_0
  matrix:
    - GENERATOR: "Visual Studio 16 2019"
      BUILDFLAGS: "/verbosity:normal"
      CMAKEARGS: ""

matrix:
  fast_finish: true

install:
- cd %APPVEYOR_BUILD_FOLDER%
- git submodule update --init --recursive --depth 1


before_build:
  - cmake --version

build_script:
  - cmake -S. -Bbuild
          -G"%GENERATOR%"
          -A x64
          -DCMAKE_BUILD_TYPE=%CONFIGURATION%
          %CMAKEARGS%
  - cmake --build build
          --config %CONFIGURATION%
          -- %BUILDFLAGS%

deploy: off
