language: cpp

dist: bionic

git:
  depth: 1
  submodules: true

script:
- gcc-10 --version
- mkdir build
- cd build
- cmake .. -DVCPKG_TARGET_TRIPLET=x64-windows-static-md
- cmake --build .

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-10
            - g++-10
      env:
         - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

before_install:
- sudo apt-get -qq update && sudo apt-get install -y autoconf cmake libtool
- sudo apt-get install -y libgtk-3-dev
- sudo apt-get install -y libbrotli-dev
- sudo apt-get install -y libbz2-dev
- sudo apt-get install -y libharfbuzz-dev
- eval "${MATRIX_EVAL}"

branches:
  only:
  - main
  - feature
