language: cpp

dist: bionic

script:
- gcc-8 --version
- mkdir build
- cd build
- cmake ..
- cmake --build .

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
      env:
         - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
- eval "${MATRIX_EVAL}"
- sudo apt-get -y install libboost-all-dev 
- sudo apt-get -y install libgtk-3-dev
