language: cpp

dist: bionic

script:
- gcc-10 --version
- mkdir build
- cd build
- cmake ..
- cmake --build .

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-10
            - g++-10
      env:
         - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

before_install:
- eval "${MATRIX_EVAL}"
- sudo apt-get -y install libboost-all-dev 
- sudo apt-get -y install libgtk-3-dev
